prompts:
- prompts/crypto_summary.txt
providers:
- id: echo
  config:
    echo: 'The price of {{coin}} is predicted to move from {{previous_price}} to {{predicted_price}}.
      WARNING: Crypto trading involves high risk. This is not financial advice.'
tests:
- vars:
    coin: Bitcoin
    previous_price: 7,400,691.5
    predicted_price: 7,511,701.87
  assert:
  - type: icontains
    value: risk
  - type: javascript
    value: output.toLowerCase().includes('not financial advice')
- vars:
    coin: Ethereum
    previous_price: 203,549.78
    predicted_price: 206,603.03
  assert:
  - type: icontains
    value: warning
- vars:
    coin: Solana
    previous_price: 8,147.36
    predicted_price: 8,269.57
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Binance Coin
    previous_price: 61,646.76
    predicted_price: 62,571.46
  assert:
  - type: icontains
    value: warning
- vars:
    coin: Bitcoin Cash
    previous_price: 35,122.22
    predicted_price: 35,649.05
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Litecoin
    previous_price: 5,161.33
    predicted_price: 5,238.75
  assert:
  - type: icontains
    value: warning
- vars:
    coin: Chainlink
    previous_price: '908.93'
    predicted_price: '922.56'
  assert:
  - type: icontains
    value: warning
- vars:
    coin: Avalanche
    previous_price: '876.83'
    predicted_price: '889.98'
  assert:
  - type: icontains
    value: warning
- vars:
    coin: Ripple
    previous_price: '133.19'
    predicted_price: '135.19'
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Polkadot
    previous_price: '117.32'
    predicted_price: '119.08'
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Cardano
    previous_price: '23.97'
    predicted_price: '24.33'
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Polygon
    previous_price: '8.70'
    predicted_price: '9.10'
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Dogecoin
    previous_price: '10.0'
    predicted_price: '10.15'
  assert:
  - type: icontains
    value: warning
