prompts:
- prompts/crypto_summary.txt
providers:
- id: echo
  config:
    echo: 'The price of {{coin}} is predicted to move from {{previous_price}} to {{predicted_price}}.
      WARNING: Crypto trading involves high risk. This is not financial advice.'
tests:
- vars:
    coin: Bitcoin
    previous_price: 7,401,669.0
    predicted_price: 7,512,694.03
  assert:
  - type: icontains
    value: risk
  - type: javascript
    value: output.toLowerCase().includes('not financial advice')
- vars:
    coin: Ethereum
    previous_price: 203,978.12
    predicted_price: 207,037.79
  assert:
  - type: icontains
    value: warning
- vars:
    coin: Solana
    previous_price: 8,169.95
    predicted_price: 8,292.5
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Binance Coin
    previous_price: 61,832.84
    predicted_price: 62,760.33
  assert:
  - type: icontains
    value: warning
- vars:
    coin: Bitcoin Cash
    previous_price: 36,308.48
    predicted_price: 36,853.11
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Litecoin
    previous_price: 5,206.76
    predicted_price: 5,284.86
  assert:
  - type: icontains
    value: warning
- vars:
    coin: Chainlink
    previous_price: '916.52'
    predicted_price: '930.27'
  assert:
  - type: icontains
    value: warning
- vars:
    coin: Avalanche
    previous_price: '882.64'
    predicted_price: '895.88'
  assert:
  - type: icontains
    value: warning
- vars:
    coin: Ripple
    previous_price: '133.71'
    predicted_price: '135.72'
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Polkadot
    previous_price: '118.7'
    predicted_price: '120.48'
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Cardano
    previous_price: '24.09'
    predicted_price: '24.45'
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Polygon
    previous_price: '8.70'
    predicted_price: '9.10'
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Dogecoin
    previous_price: '10.25'
    predicted_price: '10.4'
  assert:
  - type: icontains
    value: warning
