prompts:
- prompts/crypto_summary.txt
providers:
- id: echo
  config:
    echo: 'The price of {{coin}} is predicted to move from {{previous_price}} to {{predicted_price}}.
      WARNING: Crypto trading involves high risk. This is not financial advice.'
tests:
- vars:
    coin: Bitcoin
    previous_price: 7,388,176.5
    predicted_price: 7,498,999.15
  assert:
  - type: icontains
    value: risk
  - type: javascript
    value: output.toLowerCase().includes('not financial advice')
- vars:
    coin: Ethereum
    previous_price: 203,457.34
    predicted_price: 206,509.2
  assert:
  - type: icontains
    value: warning
- vars:
    coin: Solana
    previous_price: 8,151.49
    predicted_price: 8,273.76
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Binance Coin
    previous_price: 61,544.85
    predicted_price: 62,468.02
  assert:
  - type: icontains
    value: warning
- vars:
    coin: Bitcoin Cash
    previous_price: 35,396.95
    predicted_price: 35,927.9
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Litecoin
    previous_price: 5,169.42
    predicted_price: 5,246.96
  assert:
  - type: icontains
    value: warning
- vars:
    coin: Chainlink
    previous_price: '910.3'
    predicted_price: '923.95'
  assert:
  - type: icontains
    value: warning
- vars:
    coin: Avalanche
    previous_price: '877.35'
    predicted_price: '890.51'
  assert:
  - type: icontains
    value: warning
- vars:
    coin: Ripple
    previous_price: '133.13'
    predicted_price: '135.13'
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Polkadot
    previous_price: '117.73'
    predicted_price: '119.5'
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Cardano
    previous_price: '23.93'
    predicted_price: '24.29'
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Polygon
    previous_price: '8.70'
    predicted_price: '9.10'
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Dogecoin
    previous_price: '10.07'
    predicted_price: '10.22'
  assert:
  - type: icontains
    value: warning
